language: node_js
node_js:
    -"8.9.4"
    -"9.5.0"
before_script:
    -"npm install"
script:
    -"npm run dev"
after_script:
    -"echo Building Successful!"
branches:
    only:
        -"master"

